// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2CProtobuf.proto

package com.whg.protobuf;

public final class S2CProtobuf {
  private S2CProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginS2CVOProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .BoProtobuf.UserProto user = 1;
    /**
     * <code>optional .BoProtobuf.UserProto user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>optional .BoProtobuf.UserProto user = 1;</code>
     */
    com.whg.protobuf.BoProtobuf.UserProto getUser();
    /**
     * <code>optional .BoProtobuf.UserProto user = 1;</code>
     */
    com.whg.protobuf.BoProtobuf.UserProtoOrBuilder getUserOrBuilder();
  }
  /**
   * Protobuf type {@code BoProtobuf.LoginS2CVOProto}
   */
  public static final class LoginS2CVOProto extends
      com.google.protobuf.GeneratedMessage
      implements LoginS2CVOProtoOrBuilder {
    // Use LoginS2CVOProto.newBuilder() to construct.
    private LoginS2CVOProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginS2CVOProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginS2CVOProto defaultInstance;
    public static LoginS2CVOProto getDefaultInstance() {
      return defaultInstance;
    }

    public LoginS2CVOProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginS2CVOProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.whg.protobuf.BoProtobuf.UserProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.whg.protobuf.BoProtobuf.UserProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whg.protobuf.S2CProtobuf.internal_static_BoProtobuf_LoginS2CVOProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whg.protobuf.S2CProtobuf.internal_static_BoProtobuf_LoginS2CVOProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whg.protobuf.S2CProtobuf.LoginS2CVOProto.class, com.whg.protobuf.S2CProtobuf.LoginS2CVOProto.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginS2CVOProto> PARSER =
        new com.google.protobuf.AbstractParser<LoginS2CVOProto>() {
      public LoginS2CVOProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginS2CVOProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginS2CVOProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .BoProtobuf.UserProto user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private com.whg.protobuf.BoProtobuf.UserProto user_;
    /**
     * <code>optional .BoProtobuf.UserProto user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .BoProtobuf.UserProto user = 1;</code>
     */
    public com.whg.protobuf.BoProtobuf.UserProto getUser() {
      return user_;
    }
    /**
     * <code>optional .BoProtobuf.UserProto user = 1;</code>
     */
    public com.whg.protobuf.BoProtobuf.UserProtoOrBuilder getUserOrBuilder() {
      return user_;
    }

    private void initFields() {
      user_ = com.whg.protobuf.BoProtobuf.UserProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, user_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whg.protobuf.S2CProtobuf.LoginS2CVOProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BoProtobuf.LoginS2CVOProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.whg.protobuf.S2CProtobuf.LoginS2CVOProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whg.protobuf.S2CProtobuf.internal_static_BoProtobuf_LoginS2CVOProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whg.protobuf.S2CProtobuf.internal_static_BoProtobuf_LoginS2CVOProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whg.protobuf.S2CProtobuf.LoginS2CVOProto.class, com.whg.protobuf.S2CProtobuf.LoginS2CVOProto.Builder.class);
      }

      // Construct using com.whg.protobuf.S2CProtobuf.LoginS2CVOProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = com.whg.protobuf.BoProtobuf.UserProto.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whg.protobuf.S2CProtobuf.internal_static_BoProtobuf_LoginS2CVOProto_descriptor;
      }

      public com.whg.protobuf.S2CProtobuf.LoginS2CVOProto getDefaultInstanceForType() {
        return com.whg.protobuf.S2CProtobuf.LoginS2CVOProto.getDefaultInstance();
      }

      public com.whg.protobuf.S2CProtobuf.LoginS2CVOProto build() {
        com.whg.protobuf.S2CProtobuf.LoginS2CVOProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.whg.protobuf.S2CProtobuf.LoginS2CVOProto buildPartial() {
        com.whg.protobuf.S2CProtobuf.LoginS2CVOProto result = new com.whg.protobuf.S2CProtobuf.LoginS2CVOProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whg.protobuf.S2CProtobuf.LoginS2CVOProto) {
          return mergeFrom((com.whg.protobuf.S2CProtobuf.LoginS2CVOProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whg.protobuf.S2CProtobuf.LoginS2CVOProto other) {
        if (other == com.whg.protobuf.S2CProtobuf.LoginS2CVOProto.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whg.protobuf.S2CProtobuf.LoginS2CVOProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whg.protobuf.S2CProtobuf.LoginS2CVOProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .BoProtobuf.UserProto user = 1;
      private com.whg.protobuf.BoProtobuf.UserProto user_ = com.whg.protobuf.BoProtobuf.UserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.whg.protobuf.BoProtobuf.UserProto, com.whg.protobuf.BoProtobuf.UserProto.Builder, com.whg.protobuf.BoProtobuf.UserProtoOrBuilder> userBuilder_;
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      public com.whg.protobuf.BoProtobuf.UserProto getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      public Builder setUser(com.whg.protobuf.BoProtobuf.UserProto value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      public Builder setUser(
          com.whg.protobuf.BoProtobuf.UserProto.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      public Builder mergeUser(com.whg.protobuf.BoProtobuf.UserProto value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              user_ != com.whg.protobuf.BoProtobuf.UserProto.getDefaultInstance()) {
            user_ =
              com.whg.protobuf.BoProtobuf.UserProto.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = com.whg.protobuf.BoProtobuf.UserProto.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      public com.whg.protobuf.BoProtobuf.UserProto.Builder getUserBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      public com.whg.protobuf.BoProtobuf.UserProtoOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      /**
       * <code>optional .BoProtobuf.UserProto user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.whg.protobuf.BoProtobuf.UserProto, com.whg.protobuf.BoProtobuf.UserProto.Builder, com.whg.protobuf.BoProtobuf.UserProtoOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.whg.protobuf.BoProtobuf.UserProto, com.whg.protobuf.BoProtobuf.UserProto.Builder, com.whg.protobuf.BoProtobuf.UserProtoOrBuilder>(
                  user_,
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BoProtobuf.LoginS2CVOProto)
    }

    static {
      defaultInstance = new LoginS2CVOProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BoProtobuf.LoginS2CVOProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BoProtobuf_LoginS2CVOProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BoProtobuf_LoginS2CVOProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021S2CProtobuf.proto\022\nBoProtobuf\032\020BoProto" +
      "buf.proto\"6\n\017LoginS2CVOProto\022#\n\004user\030\001 \001" +
      "(\0132\025.BoProtobuf.UserProtoB\037\n\020com.whg.pro" +
      "tobufB\013S2CProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BoProtobuf_LoginS2CVOProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BoProtobuf_LoginS2CVOProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BoProtobuf_LoginS2CVOProto_descriptor,
              new java.lang.String[] { "User", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.whg.protobuf.BoProtobuf.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
